const militar=document.querySelector("#militar")
const civil=document.querySelector("#civil")
const nome=document.querySelector("#nome")
const marca=document.querySelector("#marca")
const cor=document.querySelector("#cor")
const portas=document.querySelector("#portas")
const blindagem=document.querySelector("#blindagem")
const municao=document.querySelector("#municao")
const btn_add=document.getElementById("btn-add")
const btn_militar=document.querySelector("#tipo-militar")
const btn_civil=document.querySelector("#tipo-civil")
const veiculosTabela=document.querySelector("#veiculosTabela")

btn_militar.addEventListener("click",()=>{
    civil.setAttribute("class","escondido")
    militar.removeAttribute("class","escondido")
    blindagem.removeAttribute("class","escondido")
    municao.removeAttribute("class","escondido")
})
btn_civil.addEventListener("click",()=>{
    militar.setAttribute("class","escondido")
    civil.removeAttribute("class","escondido")
    blindagem.setAttribute("class","escondido")
    municao.setAttribute("class","escondido")
})